factory_monitor/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', views.index, name='index'),
    path('api/machine/',include('machine.urls')),
    path('api-auth/',include('rest_framework.urls',namespace='rest_framework')),
]

users/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users' # curcial
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('activate/<user_name>/<activate_code>', views.ActiveUserView.as_view(), name="user_active"),
]

templates/Detail.html
<!DOCTYPE html>
<head>
<title>Home</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } 
</script>
<link rel="stylesheet" href="/static/css/bootstrap.min.css" >

<link href="/static/css/style.css" rel='stylesheet' type='text/css' />
<link rel="stylesheet" type="text/css" href="/static/css/style2.css">
<!-- font-awesome icons -->
<link rel="stylesheet" href="/static/css/font.css" type="text/css"/>
<link href="/static/css/font-awesome.css" rel="stylesheet">
<!-- //font-awesome icons -->
<script src="/static/js/jquery2.0.3.min.js"></script>
<script src="/static/js/raphael-min.js"></script>
<script src="/static/js/morris.js"></script>
</head>
<body>
<header class="header fixed-top clearfix">
<div class="brand">
    <a href="{% url 'index' %}" class="logo">
        FACTORY MONITOR
    </a>
    <div class="sidebar-toggle-box">
        <div class="fa fa-bars"></div>
    </div>
</div>

<div class="top-nav clearfix">
    <ul class="nav pull-right top-menu">
        <li>
            <input type="text" class="form-control search" placeholder="搜索仪器">
        </li>
        <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <img alt="" src="/static/images/bg.jpg">
                <span class="username">用户中心</span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu extended logout">
                <li><a href="#"><i class=" fa fa-suitcase"></i>我的信息</a></li>
                <li><a href="/admin/"><i class="fa fa-cog"></i>管理员入口</a></li>
                <li><a href="{% url 'users:logout' %}"><i class="fa fa-key"></i>注销</a></li>
            </ul>
        </li>
    </ul>
</div>
</header>
<aside>
    <div id="sidebar" class="nav-collapse">
        <div class="leftside-navigation">
            <ul class="sidebar-menu" id="nav-accordion">
                <li class="sub-menu">
                    <a class="active" href="{% url 'index' %}">
                        <i class=" fa fa-bar-chart-o"></i>
                        <span>仪器总览</span>
                    </a>
                    <ul class="sub">
                        <li><a href="/api/machine/detail/controler/">仪器详情</a></li>

                    </ul>
                </li>
                <li>
                    <a href="{% url 'users:login' %}">
                        <i class="fa fa-user"></i>
                        <span>返回登录</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</aside>
<section id="main-content">
	<section class="wrapper">
		<div class="machines" id="machines">
        </div>
    </section>
</section>

<!-- 四幅图 -->
<div id="Water_in" style="height:400px;width: 900px;float:right;"></div>
<div id="Water_out" style="height:400px;width: 900px;float:right;"></div>
<div id="Water_COD" style="height:400px;width: 900px;float:right;"></div>
<div id="Water_BOD" style="height:400px;width: 900px;float:right;"></div>


<!-- ECharts单文件引入 -->
<script src="http://echarts.baidu.com/build/dist/echarts-all.js"></script>
<script type="text/javascript">

    var receive_All ;
    //water_in 是出水流量列表
    var water_in = [0];
	var water_out = [0];
	var COD = [0];
	var BOD = [0];
	var x_update = [0]
	function loadAllXMLDoc()
{
	//今天的时间
	var max_length
	var mytime
	var my_t = new Date()
	var month = my_t.getMonth()+1
	//alert(month)
	var t_seq = 'time?'+'year='+my_t.getFullYear()+'&month='+month+'&day='+my_t.getDate()
    //alert('time?'+'year='+my_t.getFullYear()+'&month='+month+'&day='+my_t.getDate())
	var xmlhttp;
	if (window.XMLHttpRequest)
	{

		//  IE7+, Firefox, Chrome, Opera, Safari 浏览器执行代码
		xmlhttp=new XMLHttpRequest();
	}
	else
	{
		// IE6, IE5 浏览器执行代码
		xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
	}
	// alert(xmlhttp.responseText)
	xmlhttp.onreadystatechange=function()
	{
		if (xmlhttp.readyState==4 && xmlhttp.status==200)
		{

			receive_All = JSON.parse(xmlhttp.responseText);
			max_length = receive_All.length
			for (var i=0;i < max_length; i++){
			    water_in.push(receive_All[max_length-1-i].water_in)
			    water_out.push(receive_All[max_length-1-i].water_out)
			    COD.push(receive_All[max_length-1-i].COD)
	            BOD.push(receive_All[max_length-1-i].BOD)
	            mytime = receive_All[max_length-1-i].timestamp;
			    x_update.push(format(mytime));

			}

		}

	}
	//改一下时间
	xmlhttp.open("GET","http://127.0.0.1:8000/api/machine/controler/"+t_seq+"&format=json",true);
	xmlhttp.send();
};
	loadAllXMLDoc();

	var max_water_in = 1000;
	var max_water_out = 1000;
	var max_COD = 80;
	var max_BOD = 40;

    //var x_update 是横坐标列表

    // 基于准备好的dom，初始化echarts图表
    var Chart_water_in = echarts.init(document.getElementById("Water_in"));
	var Chart_water_out = echarts.init(document.getElementById("Water_out"));
	var Chart_COD = echarts.init(document.getElementById("Water_COD"));
	var Chart_BOD = echarts.init(document.getElementById("Water_BOD"));
	var option_water_in = {
        title : {
            text: '进水流量',
        },
        tooltip : {
            trigger: 'axis'
        },

        //右上角工具条
        toolbox: {
            show : false,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType : {show: true, type: ['line', 'bar']},
                restore : {show: true},
                saveAsImage : {show: true}
            }
        },
        calculable : true,
        xAxis : [
            {
                type : 'category',
                boundaryGap : false,
                data : x_update
            }
        ],
        yAxis : [
            {
                type : 'value',
                axisLabel : {
                    formatter: '{value} m^3/s'
                }
            }
        ],
        series : [
            {
                name:'进水流量',
                type:'line',
				color:'red',
                data:water_in,
                markPoint : {
                    data : [
                        {type : 'max', name: '最大值'},
                        {type : 'min', name: '最小值'}
                    ]
                },
                markLine : {
                    data : [
                        {type : 'average', name: '平均值',color:'black'}
                    ]
                }
            }

        ]
    };
	var option_water_out = {
        title : {
            text: '出水流量',
        },
        tooltip : {
            trigger: 'axis'
        },

        //右上角工具条
        toolbox: {
            show : false,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType : {show: true, type: ['line', 'bar']},
                restore : {show: true},
                saveAsImage : {show: true}
            }
        },
        calculable : true,
        xAxis : [
            {
                type : 'category',
                boundaryGap : false,
                data : x_update
            }
        ],
        yAxis : [
            {
                type : 'value',
                axisLabel : {
                    formatter: '{value} m^3/s'
                }
            }
        ],
        series : [
            {
                name:'出水流量',
                type:'line',
                data:water_out,
                markPoint : {
                    data : [
                        {type : 'max', name: '最大值'},
                        {type : 'min', name: '最小值'}
                    ]
                },
                markLine : {
                    data : [
                        {type : 'average', name: '平均值'}
                    ]
                }
            }

        ]
    };
	var option_COD = {
        title : {
            text: 'COD',
        },
        tooltip : {
            trigger: 'axis'
        },

        //右上角工具条
        toolbox: {
            show : false,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType : {show: true, type: ['line', 'bar']},
                restore : {show: true},
                saveAsImage : {show: true}
            }
        },
        calculable : true,
        xAxis : [
            {
                type : 'category',
                boundaryGap : false,
                data : x_update
            }
        ],
        yAxis : [
            {
                type : 'value',
            }
        ],
        series : [
            {
                name:'COD',
                type:'line',
                data:COD,
                markPoint : {
                    data : [
                        {type : 'max', name: '最大值'},
                        {type : 'min', name: '最小值'}
                    ]
                },
                markLine : {
                    data : [
                        {type : 'average', name: '平均值'}
                    ]
                }
            }

        ]
    };
	var option_BOD = {
        title : {
            text: 'BOD',
        },
        tooltip : {
            trigger: 'axis'
        },
        //右上角工具条
        toolbox: {
            show : false,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType : {show: true, type: ['line', 'bar']},
                restore : {show: true},
                saveAsImage : {show: true}
            }
        },
        calculable : true,
        xAxis : [
            {
                type : 'category',
                boundaryGap : false,
                data : x_update
            }
        ],
        yAxis : [
            {
                type : 'value'
            }
        ],
        series : [
            {
                name:'BOD',
                type:'line',
                data:BOD,
                markPoint : {
                    data : [
                        {type : 'max', name: '最大值'},
                        {type : 'min', name: '最小值'}
                    ]
                },
                markLine : {
                    data : [
                        {type : 'average', name: '平均值'}
                    ]
                }
            }

        ]
    };


    // 为echarts对象加载数据
    Chart_water_in.setOption(option_water_in);
	Chart_water_out.setOption(option_water_out);
	Chart_COD.setOption(option_COD);
	Chart_BOD.setOption(option_BOD);

	//document.getElementById("show").innerHTML=water_in
function loadXMLDoc()
{
	var receive
	var xmlhttp;
	if (window.XMLHttpRequest)
	{
		//  IE7+, Firefox, Chrome, Opera, Safari 浏览器执行代码
		xmlhttp=new XMLHttpRequest();
	}
	else
	{
		// IE6, IE5 浏览器执行代码
		xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
	}
	//alert('1: '+xmlhttp.readyState+' '+xmlhttp.status);
	xmlhttp.onreadystatechange=function()
	{
		//alert('2: '+xmlhttp.readyState+' '+xmlhttp.status)
		if (xmlhttp.readyState==4 && xmlhttp.status==200)
		{
			//document.getElementById("show").innerHTML=xmlhttp.responseText
			receive = JSON.parse(xmlhttp.responseText);
			mydate = new Date()
			water_in.push(receive.water_in);
			water_out.push(receive.water_out)
			COD.push(receive.COD)
			BOD.push(receive.BOD)
			mytime = receive.timestamp;
			x_update.push(format(mytime));
			Chart_water_in.setOption(option_water_in);
			Chart_water_out.setOption(option_water_out);
			Chart_COD.setOption(option_COD);
			Chart_BOD.setOption(option_BOD);
		};


	}
	xmlhttp.open("GET","http://127.0.0.1:8000/api/machine/controler/time/latest/?format=json",true);
	xmlhttp.send();

};

function format(mytime)
{
return mytime[11]+mytime[12]+mytime[13]+mytime[14]+mytime[15]+mytime[16]+mytime[17]+mytime[18];
};


function update()
{
loadXMLDoc()

}
    //setInterval是间隔一定市场循环调用函数
    setInterval(function(){update()},5000);


</script>
<script src="/static/js/bootstrap.js"></script>
<script src="/static/js/jquery.dcjqaccordion.2.7.js"></script>
<script src="/static/js/scripts.js"></script>
<script src="/static/js/jquery.slimscroll.js"></script>
<script src="/static/js/jquery.nicescroll.js"></script>
<script src="/static/js/jquery.scrollTo.js"></script>
</html>

templates/Detail2.html
<!DOCTYPE html>
<head>
<title>Home</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } 
</script>
<link rel="stylesheet" href="css/bootstrap.min.css" >

<link href="css/style.css" rel='stylesheet' type='text/css' />
<link rel="stylesheet" type="text/css" href="css/style2.css">
<!-- font-awesome icons -->
<link rel="stylesheet" href="css/font.css" type="text/css"/>
<link href="css/font-awesome.css" rel="stylesheet"> 
<!-- //font-awesome icons -->
<script src="js/jquery2.0.3.min.js"></script>
<script src="js/raphael-min.js"></script>
<script src="js/morris.js"></script>
</head>
<body onload="getTime()">
<header class="header fixed-top clearfix">
<div class="brand">
    <a href="index.html" class="logo">
        FACTORY MONITOR
    </a>
    <div class="sidebar-toggle-box">
        <div class="fa fa-bars"></div>
    </div>
</div>

<div class="top-nav clearfix">
    <ul class="nav pull-right top-menu">
        <li>
            <input type="text" class="form-control search" placeholder="搜索仪器">
        </li>
        <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <img alt="" src="images/bg.jpg">
                <span class="username">用户中心</span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu extended logout">
                <li><a href="#"><i class=" fa fa-suitcase"></i>我的信息</a></li>
                <li><a href="#"><i class="fa fa-cog"></i>管理员入口</a></li>
                <li><a href="login.html"><i class="fa fa-key"></i>注销</a></li>
            </ul>
        </li>
    </ul>
</div>
</header>
<aside>
    <div id="sidebar" class="nav-collapse">
        <div class="leftside-navigation">
            <ul class="sidebar-menu" id="nav-accordion">
                <li class="sub-menu">
                    <a class="active" href="index.html">
                        <i class=" fa fa-bar-chart-o"></i>
                        <span>仪器总览</span>
                    </a>
                    <ul class="sub">
                        <li><a href="Detail.html">仪器详情</a></li>
						
                    </ul>
                </li>
                <li>
                    <a href="registration/login.html">
                        <i class="fa fa-user"></i>
                        <span>返回登录</span>
                    </a>
                </li>
            </ul>            
        </div>
    </div>
</aside>
<section id="main-content">
    <section class="wrapper">
        <h2>污水处理器</h2>
        <div class="time" id="time">
        </div>
    </section>
</section>

<!-- 四幅图 -->
<div id="level" style="height:400px;width: 900px;float:right;"></div>
<div id="temperature" style="height:400px;width: 900px;float:right;"></div>
<div id="PH" style="height:400px;width: 900px;float:right;"></div>
<div id="density" style="height:400px;width: 900px;float:right;"></div>


<!-- ECharts单文件引入 -->
<script src="http://echarts.baidu.com/build/dist/echarts-all.js"></script>
<script type="text/javascript">
  
 
    //level 是出水流量列表
    var level = [0];
	var temperature = [0];
	var PH = [0];
	var density = [0];
    //var x_update 是横坐标列表
    var x_update = [0];
    // 基于准备好的dom，初始化echarts图表
    var Chart_level = echarts.init(document.getElementById("level"));
	var Chart_temperature = echarts.init(document.getElementById("temperature"));
	var Chart_PH = echarts.init(document.getElementById("PH"));
	var Chart_density = echarts.init(document.getElementById("density"));
	var option_level = {
        title : {
            text: '工厂仪器指标',
        },
        tooltip : {
            trigger: 'axis'
        },
		
        legend: {
		    x: 'center',
			borderWidth: 2,
            data:['提升泵液位']
        },
        //右上角工具条
        toolbox: {
            show : false,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType : {show: true, type: ['line', 'bar']},
                restore : {show: true},
                saveAsImage : {show: true}
            }
        },
        calculable : true,
        xAxis : [
            {
                type : 'category',
                boundaryGap : false,
                data : x_update
            }
        ],
        yAxis : [
            {
                type : 'value',
                axisLabel : {
                    formatter: '{value} m^3/s'
                }
            }
        ],
        series : [
            {
                name:'提升泵液位',
                type:'line',
                data:level,
                markPoint : {
                    data : [
                        {type : 'max', name: '最大值'},
                        {type : 'min', name: '最小值'}
                    ]
                },
                markLine : {
                    data : [
                        {type : 'average', name: '平均值'}
                    ]
                }
            }

        ]
    };
	var option_temperature = {
        title : {
            text: '工厂仪器指标',
        },
        tooltip : {
            trigger: 'axis'
        },
		
        legend: {
		    x: 'center',
			borderWidth: 2,
            data:['曝气池温度']
        },
        //右上角工具条
        toolbox: {
            show : false,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType : {show: true, type: ['line', 'bar']},
                restore : {show: true},
                saveAsImage : {show: true}
            }
        },
        calculable : true,
        xAxis : [
            {
                type : 'category',
                boundaryGap : false,
                data : x_update
            }
        ],
        yAxis : [
            {
                type : 'value',
                axisLabel : {
                    formatter: '{value} m^3/s'
                }
            }
        ],
        series : [
            {
                name:'曝气池温度',
                type:'line',
                data:temperature,
                markPoint : {
                    data : [
                        {type : 'max', name: '最大值'},
                        {type : 'min', name: '最小值'}
                    ]
                },
                markLine : {
                    data : [
                        {type : 'average', name: '平均值'}
                    ]
                }
            }

        ]
    };
	var option_PH = {
        title : {
            text: '工厂仪器指标',
        },
        tooltip : {
            trigger: 'axis'
        },
		
        legend: {
		    x: 'center',
			borderWidth: 2,
            data:['曝气池PH']
        },
        //右上角工具条
        toolbox: {
            show : false,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType : {show: true, type: ['line', 'bar']},
                restore : {show: true},
                saveAsImage : {show: true}
            }
        },
        calculable : true,
        xAxis : [
            {
                type : 'category',
                boundaryGap : false,
                data : x_update
            }
        ],
        yAxis : [
            {
                type : 'value',
                axisLabel : {
                    formatter: '{value} m^3/s'
                }
            }
        ],
        series : [
            {
                name:'曝气池PH',
                type:'line',
                data:PH,
                markPoint : {
                    data : [
                        {type : 'max', name: '最大值'},
                        {type : 'min', name: '最小值'}
                    ]
                },
                markLine : {
                    data : [
                        {type : 'average', name: '平均值'}
                    ]
                }
            }

        ]
    };
	var option_density = {
        title : {
            text: '工厂仪器指标',
        },
        tooltip : {
            trigger: 'axis'
        },
		
        legend: {
		    x: 'center',
			borderWidth: 2,
            data:['污泥浓度']
        },
        //右上角工具条
        toolbox: {
            show : false,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType : {show: true, type: ['line', 'bar']},
                restore : {show: true},
                saveAsImage : {show: true}
            }
        },
        calculable : true,
        xAxis : [
            {
                type : 'category',
                boundaryGap : false,
                data : x_update
            }
        ],
        yAxis : [
            {
                type : 'value',
                axisLabel : {
                    formatter: '{value} m^3/s'
                }
            }
        ],
        series : [
            {
                name:'污泥浓度',
                type:'line',
                data:density,
                markPoint : {
                    data : [
                        {type : 'max', name: '最大值'},
                        {type : 'min', name: '最小值'}
                    ]
                },
                markLine : {
                    data : [
                        {type : 'average', name: '平均值'}
                    ]
                }
            }

        ]
    };
    

    // 为echarts对象加载数据
    Chart_level.setOption(option_level);
	Chart_temperature.setOption(option_temperature);
	Chart_PH.setOption(option_PH);
	Chart_density.setOption(option_density);

	//document.getElementById("show").innerHTML=level
function loadXMLDoc()
{
	var receive
	var xmlhttp;
	if (window.XMLHttpRequest)
	{
	
		//  IE7+, Firefox, Chrome, Opera, Safari 浏览器执行代码
		xmlhttp=new XMLHttpRequest();
	}
	else
	{
		// IE6, IE5 浏览器执行代码
		xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
	}
	xmlhttp.onreadystatechange=function()
	{
		if (xmlhttp.readyState==4 && xmlhttp.status==200)
		{	
			//document.getElementById("show").innerHTML=xmlhttp.responseText
			receive = JSON.parse(xmlhttp.responseText);
			mydate = new Date()
			level.push(receive.level);
			temperature.push(receive.temperature)
			PH.push(receive.PH)
			density.push(receive.density)
			mytime = receive.timestamp;
			x_update.push(format(mytime));
			Chart_level.setOption(option_level);
			Chart_temperature.setOption(option_temperature);
			Chart_PH.setOption(option_PH);
			Chart_density.setOption(option_density);
		}
		xmlhttp.readyState=0
		
	}
	xmlhttp.open("GET","http://106.15.230.111/api/machine/processor/time/latest/?format=json",true);
	xmlhttp.send();
};

function format(mytime)
{
return mytime[11]+mytime[12]+mytime[13]+mytime[14]+mytime[15]+mytime[16]+mytime[17]+mytime[18];
};

function update()
{ 
loadXMLDoc()
}
    //setInterval是间隔一定市场循环调用函数
    setInterval(function(){update()},300);


</script>
<script src="js/bootstrap.js"></script>
<script src="js/jquery.dcjqaccordion.2.7.js"></script>
<script src="js/scripts.js"></script>
<script src="js/jquery.slimscroll.js"></script>
<script src="js/jquery.nicescroll.js"></script>
<script src="js/jquery.scrollTo.js"></script>
</html>

templates/index.html
<!DOCTYPE html>
<head>
<title>Home</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } 
</script>
<link rel="stylesheet" href="/static/css/bootstrap.min.css" >

<link href="/static/css/style.css" rel='stylesheet' type='text/css' />
<!-- font-awesome icons -->
<link rel="stylesheet" href="/static/css/font.css" type="text/css"/>
<link href="/static/css/font-awesome.css" rel="stylesheet"> 
<!-- //font-awesome icons -->
<script src="/static/js/jquery2.0.3.min.js"></script>
<script src="/static/js/raphael-min.js"></script>
<script src="/static/js/morris.js"></script>
</head>
<body>
    <header class="header fixed-top clearfix">

    <div class="brand">
        <a href="/" class="logo">
            FACTORY MONITOR
        </a>
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars"></div>
        </div>
    </div>


    <div class="top-nav clearfix">

        <ul class="nav pull-right top-menu">
            <li>
                <form id="searchfrom" action="/api/machine/detail/search/" method="post">
                    <input type="text" name="machine" class="form-control search" onkeyup='revalue(this.value)' placeholder="搜索仪器">
                </form>

            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <img alt="" src="/static/images/bg.jpg">
                    <span class="username">用户中心</span>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu extended logout">
                    <li><a href="#"><i class=" fa fa-suitcase"></i>我的信息</a></li>
                    <li><a href="/admin"><i class="fa fa-cog"></i>管理员入口</a></li>
                    <li><a href="{% url 'users:logout' %}?next={{request.path}}"><i class="fa fa-key"></i>注销</a></li>
                </ul>
            </li>
           
        </ul>
    </div>
    </header>
    <aside>
        <div id="sidebar" class="nav-collapse">

            <div class="leftside-navigation">
                <ul class="sidebar-menu" id="nav-accordion">
                    <li>
                        <a class="active" href="/">
                            <i class="fa fa-dashboard"></i>
                            <span>仪器总览</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'users:login' %}?next={{ request.path }}">
                            <i class="fa fa-user"></i>
                            <span>返回登录</span>
                        </a>
                    </li>
                </ul>            
            </div>
        </div>
    </aside>
    <section id="main-content">
        <section class="wrapper">
            <div class="machines" id="machines">
                <div class="instrument">
                    <img src="/static/images/machine1.jpeg">
                    <div class="right=block">
                        <table class="instrument_info">
                            <tr colspan="2">
                                <td class="Controler">污水进出控制器</td>
                                <td>编号：1</td>   
                            </tr>
                            <tr>
                                <td class="water_in">进水流量：</td>
                                <td class="water_out">出水流量：</td>
                            </tr>
                            <tr>
                                <td class="COD">出水COD：</td>   
                                <td class="BOD">出水BOD：</td>
                            </tr>
                        </table>
                        <a href="/api/machine/detail/controler/" class=" button pink detail-info">详情</a>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="instrument">
                    <img src="/static/images/machine2.jpeg">
                    <table class="instrument_info">
                        <tr colspan="2">
                            <td class="Processor">污水处理器</td>
                            <td>编号：2</td>   
                        </tr>
                        <tr>
                                <td class="level">提升泵液位：</td>
                                <td class="temperature">曝气池温度：</td>
                            </tr>
                            <tr>
                                <td class="PH">曝气池PH：</td>   
                                <td class="density">污泥浓度：</td>
                            </tr>
                        </table>
                        <a href="/api/machine/detail/processor/" class=" button pink detail-info">详情</a>
                    <div class="clear"></div>
                </div>
            </div>
    </section>
    </section>
    <script src="/static/js/ajax.js"></script>
    <script>
            $.getJSON("/api/machine/controler/time/latest/",function(msg) {
                $.each(msg, function (index, sport) {
                        $(".water_in").html(sport.water_in);
                        $(".water_out").html(sport.water_out);
                        $(".COD").html(sport.COD);
                        $(".BOD").html(sport.BOD);
                });
            });

             $.getJSON("/api/machine/processor/time/latest/",function(msg) {
                $.each(msg, function (index, sport) {
                    $(".level").html(sport.level);
                    $(".temperature").html(sport.temperature);
                    $(".PH").html(sport.PH);
                    $(".density").html(sport.density);
                })
            });
    </script>
    <script src="/static/js/bootstrap.js"></script>
    <script src="/static/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="/static/js/scripts.js"></script>
    <script src="/static/js/jquery.slimscroll.js"></script>
    <script src="/static/js/jquery.nicescroll.js"></script>

    <script src="/static/js/jquery.scrollTo.js"></script>
</body>
</html>